### PR TITLE
logical reasoning for dumb folfs, vol. 1

### PR DESCRIPTION
**Pull request by Genderfluid**
-w-

### CODE REVIEW

**Comment by magicalbunny31** [comment]
uwu owo uwu

**Comment by Genderfluid** [comment]
So are you gonna buy it or?

**Comment by Genderfluid** [comment]
Otherwise I'll beat you to it.

**Comment by magicalbunny31** [comment]
uh oh!

**Comment by magicalbunny31** [comment]
i can't be asked to do it anyway right now, man

**Pull request closed without merging**
